const seeds = [
  {
    name: "John",
    location: "New York",
    capacity: 30,
    isAvailable: true,
  },
  {
    name: "Alice",
    location: "Los Angeles",
    capacity: 25,
    isAvailable: false,
  },
  {
    name: "Bob",
    location: "Chicago",
    capacity: 40,
    isAvailable: true,
  },
  {
    name: "Ella",
    location: "San Francisco",
    capacity: 35,
    isAvailable: false,
  },
  {
    name: "Mike",
    location: "Miami",
    capacity: 20,
    isAvailable: true,
  },
  {
    name: "Sara",
    location: "Seattle",
    capacity: 50,
    isAvailable: true,
  },
  {
    name: "David",
    location: "Boston",
    capacity: 28,
    isAvailable: false,
  },
  {
    name: "Emily",
    location: "Austin",
    capacity: 45,
    isAvailable: true,
  },
  {
    name: "Alex",
    location: "Denver",
    capacity: 33,
    isAvailable: false,
  },
  {
    name: "Grace",
    location: "Phoenix",
    capacity: 38,
    isAvailable: true,
  },
  {
    name: "Daniel",
    location: "Philadelphia",
    capacity: 22,
    isAvailable: false,
  },
  {
    name: "Olivia",
    location: "San Diego",
    capacity: 27,
    isAvailable: true,
  },
  {
    name: "Liam",
    location: "Dallas",
    capacity: 42,
    isAvailable: true,
  },
  {
    name: "Sophia",
    location: "Houston",
    capacity: 32,
    isAvailable: false,
  },
  {
    name: "William",
    location: "Atlanta",
    capacity: 37,
    isAvailable: true,
  },
  {
    name: "Ava",
    location: "Portland",
    capacity: 48,
    isAvailable: false,
  },
  {
    name: "Mason",
    location: "Orlando",
    capacity: 29,
    isAvailable: true,
  },
  {
    name: "Emma",
    location: "Nashville",
    capacity: 24,
    isAvailable: true,
  },
  {
    name: "Liam",
    location: "Las Vegas",
    capacity: 36,
    isAvailable: false,
  },
  {
    name: "Sophia",
    location: "Denver",
    capacity: 31,
    isAvailable: true,
  },
];
